export const produtos = [
  {
    id: 1,
    nome: "Camiseta",
    descricao: "Camiseta de algodão branca",
    valorUnitario: 25.99,
    categoria: "Roupas",
  },
  {
    id: 2,
    nome: "Tênis",
    descricao: "Tênis esportivo preto",
    valorUnitario: 89.99,
    categoria: "Calçados",
  },
  {
    id: 3,
    nome: "Celular",
    descricao: "Smartphone de última geração",
    valorUnitario: 799.99,
    categoria: "Eletrônicos",
  },
  {
    id: 4,
    nome: "Livro",
    descricao: "Romance de ficção científica",
    valorUnitario: 12.5,
    categoria: "Livros",
  },
  {
    id: 5,
    nome: "Mochila",
    descricao: "Mochila resistente para viagens",
    valorUnitario: 49.75,
    categoria: "Acessórios",
  },
  {
    id: 6,
    nome: "Fones de Ouvido",
    descricao: "Fones sem fio com cancelamento de ruído",
    valorUnitario: 129.99,
    categoria: "Eletrônicos",
  },
  {
    id: 7,
    nome: "Caneca",
    descricao: "Caneca de porcelana com estampa",
    valorUnitario: 8.75,
    categoria: "Casa",
  },
  {
    id: 8,
    nome: "Bicicleta",
    descricao: "Bicicleta urbana de alumínio",
    valorUnitario: 299.0,
    categoria: "Esportes",
  },
  {
    id: 9,
    nome: "Chapéu",
    descricao: "Chapéu de praia com aba larga",
    valorUnitario: 15.2,
    categoria: "Acessórios",
  },
  {
    id: 10,
    nome: "Cadeira de Escritório",
    descricao: "Cadeira ergonômica para escritório",
    valorUnitario: 149.9,
    categoria: "Móveis",
  },
  {
    id: 11,
    nome: "Monitor",
    descricao: "Monitor de alta definição 27 polegadas",
    valorUnitario: 249.5,
    categoria: "Eletrônicos",
  },
  {
    id: 12,
    nome: "Maquiagem",
    descricao: "Kit de maquiagem profissional",
    valorUnitario: 55.25,
    categoria: "Beleza",
  },
  {
    id: 13,
    nome: "Barbeador Elétrico",
    descricao: "Barbeador recarregável com múltiplas lâminas",
    valorUnitario: 39.99,
    categoria: "Cuidados Pessoais",
  },
  {
    id: 14,
    nome: "Máquina de Café",
    descricao: "Máquina automática para café expresso",
    valorUnitario: 179.75,
    categoria: "Eletrodomésticos",
  },
  {
    id: 15,
    nome: "Luminária",
    descricao: "Luminária de mesa flexível",
    valorUnitario: 20.5,
    categoria: "Decoração",
  },
  {
    id: 16,
    nome: "HD Externo",
    descricao: "Unidade de armazenamento externo 1TB",
    valorUnitario: 79.9,
    categoria: "Tecnologia",
  },
  {
    id: 17,
    nome: "Guarda-Chuva",
    descricao: "Guarda-chuva compacto resistente ao vento",
    valorUnitario: 14.99,
    categoria: "Acessórios",
  },
  {
    id: 18,
    nome: "Panela Antiaderente",
    descricao: "Panela de alta qualidade revestida",
    valorUnitario: 32.25,
    categoria: "Cozinha",
  },
  {
    id: 19,
    nome: "Skate",
    descricao: "Skate profissional com estampa exclusiva",
    valorUnitario: 69.5,
    categoria: "Esportes",
  },
  {
    id: 20,
    nome: "Relógio",
    descricao: "Relógio analógico resistente à água",
    valorUnitario: 99.99,
    categoria: "Acessórios",
  },
];
